apiVersion: apps/v1
kind: Deployment
metadata:
  name: php74
spec:
  replicas: 1
  selector:
    matchLabels:
      app: php74
  template:
    metadata:
      labels:
        app: php74
    spec:
      containers:
        - name: php
          image: registry.example.com/my-php74:latest
          ports:
            - containerPort: 9000
          volumeMounts:
            - name: php-storage
              mountPath: /var/www/html
      volumes:
        - name: php-storage
          persistentVolumeClaim:
            claimName: php-pvc
